@startuml class_diag

class Utilisateur
Utilisateur : -nom_utilisateur
Utilisateur : -mot_de_passe
Utilisateur : -est_admin
Utilisateur "*" -- "*" Service
(Utilisateur, Service) . Favorie
Utilisateur "*" -- "*" Service
(Utilisateur, Service) . Avis
Utilisateur "1" -- "*" Service : Posséder

class Service
Service : -latitude
Service : -longitude
Service : -type
Service : -titre
Service "1" -- "*" Image : Avoir

class Image
Image : -lien

class Favorie
Favorie : -date_ajout

class Avis
Avis : -etoiles
Avis : -commentaire


@enduml