@startuml class_diag

class Public_user
Public_user : -pu_coordinates
Public_user "*" -- "*" Service
(Public_user, Service) . Search

class Account
Account : -username
Account : -password
Account : +change_pass(current, new)
Account : +change_username(current, new)
Account : +delete_acc()

class Admin_Account
Admin_Account ---|> Account
Admin_Account "0,1" -- "*" User_Account : manage
Admin_Account "0,1" -- "*" Service : alter

class User_Account
User_Account : -status
User_Account ---|> Account
User_Account ---|> Public_user
User_Account "1" -- "*" plan : Create
User_Account "*" -- "*" Service
(User_Account, Service) . Favorite
User_Account "*" -- "*" Service
(User_Account, Service) . Rating
User_Account "1" -- "*" Service : Manage personnal

class Search
Search : -distance

class Service
Service : -latitude
Service : -longitude
Service : -type
Service : -title
Service : -address
Service "1" -- "*" Image : have

class Image
Image : -url

class Stop
Stop : -stop_datetime

class plan
plan : -plan_title
plan : -plan_description
plan : -plan_start
plan : -plan_end
plan "*" --o "*" Service
(plan, Service) . Stop

class Favorite
Favorite : -add_date

class Rating
Rating : -stars
Rating : -comment


@enduml