@startuml class_diag

class User
User : -username
User : -password
User : -role
User "*" -- "*" Service
(User, Service) . Favorite
User "*" -- "*" Service
(User, Service) . Rating
User "1" -- "*" Service : Own

class Service
Service : -latitude
Service : -longitude
Service : -type
Service : -title
Service "1" -- "*" Image : Have

class Image
Image : -url

class Favorite
Favorite : -add_date

class Rating
Rating : -stars
Rating : -comment


@enduml