@startuml nearby_seq
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
usr -> fr : Demander les services à proximité
activate usr
activate fr
fr -> fr : Obtenir les coordonnées d'utilisateur/visiteur
fr -> sys : Demander des services à proximité des coordonnées
activate sys
sys -> db : Interroger les lieux à proximité des coordonnées
activate db
db --> sys : Envoyer les résultats de la requête
deactivate db
alt Requête non vide
    sys --> fr : Rendre la page web des services disponibles
else else
    sys --> fr : Afficher un message personnalisé
    deactivate sys
end
deactivate sys
@enduml


@startuml map_nearby_seq
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
usr -> sys : Demander une page Web de sélection de carte
activate usr
activate sys
sys --> fr : Rendre la page web 
activate fr
usr -> fr : Sélectionner un emplacement dans la carte
fr -> sys : Demander les services à proximité des coordonnées sélectionnées
sys -> db : Interroger les services à proximité des coordonnées
activate db
db --> sys : Envoyer les résultats de la requête
deactivate db
alt Requête non vide
    sys --> fr : Rendre la page web des services disponibles
else else
    sys --> fr : Rendre un message d'erreur
    deactivate sys
end
@enduml


@startuml sign_in
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
activate usr
usr -> sys : Demander la page Web de connexion
sys --> fr : Rendre la page web
activate fr
usr -> fr : Remplir le formulaire d'authentification
fr -> fr : Valider le formulaire
alt formulaire valide
    fr -> sys : Envoyer le formulaire
    activate sys
sys -> db : Demander le nom d'utilisateur et mot de passe
activate db
db --> sys : Envoyer les résultats de la requête
deactivate db
alt utilisateur existe
    sys -> fr : authentifier l'utilisateur
else else
    sys -> fr : Rendre un message d'erreur         
end
else else
    loop formulaire non valide
        fr --> usr : Rendre un message d'erreur\net redemander au utilisateur de\nremplire ses données
        usr -> fr : Remplir le formulaire d'authentification
        fr -> fr : Valider le formulaire
    end
end
@enduml


@startuml add_favourites
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
activate usr
activate fr
usr -> fr : demande d'ajout d'un service aux favoris
fr -> sys : Envoyer une demande avec l'identificateur de service
sys -> db : Interroger ce service à partir des favoris de l'utilisateur
activate sys
activate db
db --> sys : Envoyer les résultats de la requête
deactivate db
alt service n'existe pas
    sys -> db : Ajouter un service aux favoris de l'utilisateur
    activate db
    deactivate db
    sys --> fr : Notifier le message de réussite
else else
    sys --> fr : Notifier l'utilisateur   
end
@enduml


@startuml register_user
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
usr -> sys : Demander la page Web d'inscription
activate usr
activate sys
sys --> fr : Rendre la page web
activate fr
usr -> fr :Remplir le formulaire d'inscription
fr -> fr : Vérifier la validité des informations du formulaire
alt formulaire valide
    fr -> sys : Soumettre le formulaire
    sys -> db : Demander le nom d'utilisateur
    activate db
    db --> sys : Envoyer les résultats de la requête
    deactivate db
    alt nom d'utilisateur n'existe pas
        sys -> db : Ajouter l'utilisateur
        activate db
        deactivate db
    else else
        sys -> fr : Rendre un message d'erreur
    end
else else
    fr --> usr : Rendre un message d'erreur
end
@enduml

@startuml modify_personnal_service
actor Utilisateur as usr
participant "Interface graphique" as fr
participant "Système" as sys
participant "Base de données" as db
activate usr
usr -> sys : Demander une page de modification d'un service
activate sys
sys --> fr : Rendre la page web
activate fr
usr -> fr : Remplir de nouvelles informations
fr -> fr : Valider le formulaire
alt formulaire valide
    fr -> sys : Soumettre le formulaire
    sys -> db : Interroger les services de l'utilisateur
    activate db
    db --> sys : Envoyer les résultats de la requête
    deactivate db
    alt le service à modifier existe dans la requête
        sys -> db : Mettre à jour les informations du service
        activate db
        deactivate db
        sys -> fr : Notifier la réussite
    else else
        sys -> fr : Rendre un message d'erreur
    end
else else
    fr --> usr : Rendre un message d'erreur
end
@enduml