# Generated by Django 4.0.3 on 2022-05-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='adress',
        ),
    ]
