# Generated by Django 4.0.3 on 2022-05-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50, unique=True)),
                ('admin_hash', models.CharField(max_length=200)),
                ('admin_salt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_title', models.CharField(max_length=30)),
                ('plan_description', models.CharField(max_length=100)),
                ('plan_start', models.DateField()),
                ('plan_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('comment_str', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('service_title', models.CharField(max_length=40)),
                ('service_type', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_hash', models.CharField(max_length=200)),
                ('user_salt', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=15)),
                ('history_on', models.BooleanField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'banned', 'suspended'])), name='status_value_in'),
        ),
        migrations.AddField(
            model_name='stop',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plan'),
        ),
        migrations.AddField(
            model_name='stop',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='image',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('plan_id', 'service_id', 'stop_datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('latitude', 'longitude', 'service_title')},
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('user_id', 'search_str')},
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('stars__gte', 0), ('stars__lte', 5)), name='stars_gte_0_lte_5'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'service_id')},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('plan_title', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_url', 'service_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'service_id')},
        ),
    ]
